id = "Yalgrin.WineBridgePlugin"
name = "Wine Bridge Plugin"
author = "Yalgrin"
version = "0.1"
module = "WineBridgePlugin.dll"

# Troubleshooting link to be shown on addons view
help_link = "https://github.com/Yalgrin/playnite-wine-bridge-plugin/wiki"

# Source code link to be shown on addons view
source_link = "https://github.com/Yalgrin/playnite-wine-bridge-plugin"

# Sponsor links to be shown on addons view
[[sponsor_links]]
name = "Ko-fi"
url = "https://ko-fi.com/yalgrin"